### ISSUE TITLE
Added Dutch translation

### ISSUE THREAD

**Issue by Libre4IT** [Mnkai/PGPClipper#14]
Added Dutch translation. Posted as export to GitHub Gist. Used Stringlate.

**Comment by Mnkai** [comment]
Thank you for your participation, please submit your translation via transifix or pull request of this Git repository.

**Comment by Libre4IT** [comment]
Dutch translation done through Transifex (42 strings to review/ready for use)

**Comment by Mnkai** [comment]
Added via commit 8316a54b780d7c22f62462ee0ec8443b64d96a37
