### ISSUE TITLE
Theme settings does not work for PGPClipper

### ISSUE THREAD

**Issue by drqamranbashir** [Mnkai/PGPClipper#17]
#### Expected behavior
When we click on theme settings and change theme from light to dark , theme of app should change to dark.

#### Actual behavior
Theme does not change from light to dark.

#### How to reproduce
Open PGPclipper app.
Swipe down to theme settings.
Change theme from light to dark.

* Browser: PGPClipper 0.21
* Operating system: Android 7.0

#### Recording Of The Bug
https://youtu.be/MVfYPcx_eTo

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@drqamranbashir/theme-settings-does-not-work-for-pgpclipper">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Mnkai** [comment]
Thank you for reporting.

Dark theme setting was intended for decryption/encryption dialog, and setting’s theme was not implemented by design. But since it can be confusing, I will also add dark theme support on setting page itself (hopefully) on the next release.

**Comment by Mnkai** [comment]
Implemented in commit 41fa878f0e3c4274684ddf807b85d7301e6c282e
