### ISSUE TITLE
There are no bug reports

### ISSUE THREAD

**Issue by Mnkai** [Mnkai/PGPClipper#2]
# There is no bug!
Hey, come on. There should be bugs <i>somewhere</i>. Give me bug reports. I would be glad to debug them. So, yes- no bug is a bug here.

# Other then bug reports, what can we do to help this project?
You can always provide me translations. Russian, Spanish, Chinese... you name it!
Also, you will notice it's crappy logo. Yes, I admit I'm very bad at design. You can provide me a nice logo (and maybe other graphical assets required in Google Play Store).

# I want (this) function! & Questions?
You can always send mail to my application's support mail address (in Google Play store), or you can make issue here.

**Comment by ibanferreira** [comment]
I can provide you translations to Spanish, Portuguese and French.

**Comment by Mnkai** [comment]
@ibanferreira Since there are no translation frameworks yet, you can just fork this project and make i18n string xml files using appropriate tool - and make PR request.

If you think using Transifex - https://www.transifex.com/ is a good idea, I'll make organization and allow other users to translate using that platform. For suggestion, make a seperate issue about that.

This issue is just for notification, and I didn't want to be too long.

**Comment by Mnkai** [comment]
Update, I made Transifex organization and project. You can upload current translated xml or propose new languages at https://www.transifex.com/mnetwork/pgpclipper/ as posted in front README.

**Comment by ibanferreira** [comment]
Cool thanks!
