### ISSUE TITLE
Clipboard insecure for plaintext

### ISSUE THREAD

**Issue by PacoBell** [Mnkai/PGPClipper#4]
Isn't the global clipboard able to be monitored by pretty much any app? How is this app supposed to claim security if this is the case?

**Comment by Mnkai** [comment]
This app does not reveal decrypted text to clipboard. Only encrypted ASCII armored pgp block will be accessable to other apps in Android system.
Quick reply function also takes input (plaim text) directly from user, and sends encrypted data to system's shared clipboard.

**Comment by falsechicken** [comment]
Thanks for this app. I personally have not had to use it since most of the apps I use have pgp support built in but I like knowing its in my tool kit if I need it.

**Comment by Mnkai** [comment]
@falsechicken Thanks for using!
