### ISSUE TITLE
OpenPGP API v9

### ISSUE THREAD

**Issue by dschuermann** [Mnkai/PGPClipper#5]
Hi, OpenKeychain dev here. Great to see more projects using the API. I added PGPClipper to https://www.openkeychain.org/apps/

I saw you use v8 of our API. We are now at v9 with OpenKeychain 3.6 also fixing a nasty bug inside the API and library leading to truncated data. We have a changelog at https://github.com/open-keychain/openpgp-api/blob/master/CHANGELOG.md for migration help. If you have any remaining questions I am here to assist :)

**Comment by Mnkai** [comment]
Will upgrade to v9 when I'm back from vacation :)

Thanks for adding this project to Openkeychain's apps page! And also thanks for nice Openkeychain API which made this app possible!

**Comment by falsechicken** [comment]
:+1: . Thanks for the work @Mnkai and @dschuermann !

**Comment by Mnkai** [comment]
Migrated to API v9 in commit f1a3c1bf2cc3917f2b1c77b5360ccb4d53e30be8, will test and this change will be reflected in future release.
