### ISSUE TITLE
Version displayed at Google Play and actual version of the app don't match

### ISSUE THREAD

**Issue by ibanferreira** [Mnkai/PGPClipper#7]
Hi again,

Google Play store is showing 0.2 as the current version of the app but when downloaded
we get the 0.12 version.

**Comment by Mnkai** [comment]
Oh, that was mistake. I changed it to correct version in commit 3dc25949b5910d595579988fb6b4adc3d503a093 - which is after the release of 0.12.
Since I was lazy, and nobody seems to care about the version number - I just didn't update it.

**Comment by Mnkai** [comment]
Version code is changed back to 0.2 in commit 173e17bdf8735c9ab22b178775bd289c9715de0e - so Play Store users will see 0.2 twice after 0.2 release.

**Comment by ibanferreira** [comment]
Cool, thanks!
