### ISSUE TITLE
Crash on 0.2 when tapping the decrypted data result field

### ISSUE THREAD

**Issue by ibanferreira** [Mnkai/PGPClipper#8]
Hello,

I finally could test version 0.2. 

After processing successfully some data from the clipboard, the application crashes every time you tap the decrypted data result field.

https://gist.github.com/anonymous/a5342d08035326ff1e86

**Comment by Mnkai** [comment]
Hello,

To reproduce this bug, I need some more information. It looks like it's crashing while trying to parse reply email address (which references replying PGP key).

1. Is decryption successful?
2. Is the message signed?
3. Did you enabled NFC token feature?

From my side, decrypting message with or without signature succeeded (NFC token feature enabled), and quick reply was working correctly. I was not able to reproduce this bug in this condition. (Nexus 5, Android 6 Stock)

**Comment by ibanferreira** [comment]
Here you have:

1. Yes, the decryption was successful (and the crash happens once the decrypted text is displayed and you tap on it)
2. The message is signed.
3. NFC authentication is disabled.

More information: the test was done in a Nexus 4, with the Android 5.1.1 stock version and the encrypted data was copied from Gmail application.

**Comment by Mnkai** [comment]
I've disabled NFC auth, but was still not able to reproduce bug.

Have you tried updating OpenKeychain?
Also, does signature label have email address closed with <>? (Had to ask about this first...)
![screenshot_20151112-223919](https://cloud.githubusercontent.com/assets/10909652/11119706/bb98e9d6-898e-11e5-87af-5420357e81c5.png)

I'll be installing some emulators to emulate Nexus 4 w/ 5.1.1 stock. This crashing is not expected.

**Comment by ibanferreira** [comment]
That's how it looks the signature:

Signature status:0
(Facebook, Inc.) 

Actually the bug must be due to the absence of an e-mail address in the signature.

The decrypted data is actually an email notification from Facebook which appears to use a PGP key without an associated email.

**Comment by Mnkai** [comment]
I did not expect signature without e-mail address... I'll try to fix that issue by treating signature without mail address as non-signed message when quick replying.

**Comment by Mnkai** [comment]
Quick fix in commit 9cca9b114e9002f4e9ac79cc8d43afe611e30e2a, could please check if this issue has been fixed?

Expected behavior: No crash when try to quick reply, user will be able to select recepient manually.

**Comment by ibanferreira** [comment]
Sorry, it still crashes

https://gist.github.com/anonymous/bd2d85bef5ef6c26f90a

**Comment by Mnkai** [comment]
Next fix try at commit bdc4378d951bf95101a667b1a1afcfc467a877ed, please try that.
Hopefully, it will catch StringIndexOutOfBoundsException - which is not checked and not caught at runtime at previous commit.

**Comment by ibanferreira** [comment]
Ok, it looks fine now, when tapping it shows the prompt where you can manually fill the recipient.

**Comment by Mnkai** [comment]
Good news! Glad to hear that it's working.
