### ISSUE TITLE
Add fingerprint auth in PGPClipper

### ISSUE THREAD

**Issue by Mnkai** [Mnkai/PGPClipper#9]
Once I buy Nexus 5X.
ATM, no money to buy one.

**Comment by Mnkai** [comment]
Bought one. (Wallet's status: Bankruptcy...:P)
May require using Android KeyChain for fingerprint integration. Will make seperate issue once it's clear that Android Keychain is required.

**Comment by Mnkai** [comment]
Seems it requires Android Key'Store' impl, will work on this after API v10 migration.

**Comment by Mnkai** [comment]
(issue reference - #10)

**Comment by LaruYan** [comment]
wallet status:bankruptc. XD... Hope your financial condition go better.

Lets back to topic, Could we distinguish individual fingerprints using your keystore method? For example, My finger to unlock Key A, Someone else's finger to Key B.

As I saw on marshmallow docs, the api just notifies to an app whether this fingerprint are registered on this device.
http://www.androidpolice.com/2015/10/19/google-lays-out-requirements-for-fingerprint-sensors-in-android-6-0/

**Comment by Mnkai** [comment]
@LaruYan Unfortunately, app cannot access fingerprint reader data, and Android API does not provide which finger is scanned at the moment.

**Comment by LaruYan** [comment]
@Mnkai Oh. Okay I understood. On System app, the Nexus Imprint setting, does recognizes individual fingers so I hoped better sights on this. unfortunately, as you say, that's impossible at this moment.

Personally, I wish my English poor enough to misunderstood the doc. Anyway my English is very poor actually. :)

**Comment by Mnkai** [comment]
Too busy ATM, will close for now and reopen when there are enough requests.
